---

- name: generate scylla_servers.yml for monitoring
  script: files/minigenconfig.py --cluster-name {{ scylla_cluster_name }} --api-string http://{{ scylla_api_address }}:{{ scylla_api_port }}
  args:
    executable: "/usr/bin/env python3"
  register: genconfig

- name: store output in a file
  copy:
    content: "{{ genconfig.stdout }}"
    dest: ./scylla_servers.yml
  delegate_to: localhost

